NCSConstant.SkinComponents = {
    { name = 'sex', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'face', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'skin', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'hair_1', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'hair_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'hair_color_1', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'hair_color_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'beard_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'beard_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'beard_3', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'beard_4', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'tshirt_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'tshirt_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'tshirt_1' },
    { name = 'torso_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'torso_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'torso_1' },
    { name = 'decals_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'decals_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'decals_1' },
    { name = 'arms', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'arms_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'pants_1', defaultValue = 0, min = 0, zoomOffset = 0.8, camOffset = -0.5 },
    { name = 'pants_2', defaultValue = 0, min = 0, zoomOffset = 0.8, camOffset = -0.5, textureof = 'pants_1' },
    { name = 'shoes_1', defaultValue = 0, min = 0, zoomOffset = 0.8, camOffset = -0.8 },
    { name = 'shoes_2', defaultValue = 0, min = 0, zoomOffset = 0.8, camOffset = -0.8, textureof = 'shoes_1' },
    { name = 'mask_1', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'mask_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65, textureof = 'mask_1' },
    { name = 'bproof_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'bproof_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'bproof_1' },
    { name = 'chain_1', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'chain_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65, textureof = 'chain_1' },
    { name = 'helmet_1', defaultValue = -1, min = -1, zoomOffset = 0.6, camOffset = 0.65, componentId = 0 },
    { name = 'helmet_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65, textureof = 'helmet_1' },
    { name = 'glasses_1', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65 },
    { name = 'glasses_2', defaultValue = 0, min = 0, zoomOffset = 0.6, camOffset = 0.65, textureof = 'glasses_1' },
    { name = 'watches_1', defaultValue = -1, min = -1, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'watches_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'watches_1' },
    { name = 'bracelets_1', defaultValue = -1, min = -1, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'bracelets_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'bracelets_1' },
    { name = 'bags_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'bags_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15, textureof = 'bags_1' },
    { name = 'eye_color', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'eyebrows_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'eyebrows_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'eyebrows_3', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'eyebrows_4', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'makeup_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'makeup_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'makeup_3', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'makeup_4', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'lipstick_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'lipstick_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'lipstick_3', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'lipstick_4', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'ears_1', defaultValue = -1, min = -1, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'ears_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65, textureof = 'ears_1' },
    { name = 'chest_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'chest_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'chest_3', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'bodyb_1', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'bodyb_2', defaultValue = 0, min = 0, zoomOffset = 0.75, camOffset = 0.15 },
    { name = 'age_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'age_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'blemishes_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'blemishes_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'blush_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'blush_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'blush_3', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'complexion_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'complexion_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'sun_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'sun_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'moles_1', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 },
    { name = 'moles_2', defaultValue = 0, min = 0, zoomOffset = 0.4, camOffset = 0.65 }
}